# Generated by Django 3.2.5 on 2021-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
